version: '3.8'
services:
  dev-landing:
    image: node:18
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "cd frontend-landing && npm run dev"
    ports:
      - "3000:3000"
  dev-console:
    image: node:18
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "cd frontend-console && npm start"
    ports:
      - "3001:3001"