# This is a basic workflow to help you get started with Actions

name: DEV

# Controls when the workflow will run
on:
  push:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          envkey_AWS_DEFAULT_REGION: ap-southeast-1
          envkey_AWS_EC2_METADATA_DISABLED: true

      # Runs a single command using the runners shell
      - name: Deploy to dev environment
        run: |
          sh deploy.sh test
